### ISSUE TITLE
Default språk bør være norsk bokmål

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/static-rdf-server#34]
Uten å bruke modHeader får jeg engelsk som default språk. 
Jeg får også ofte spørsmål på hvorfor bare engelsk versjon vises (ikke alle vet/bruker modHeader). 

nb bør velges, når nb er et av språkene i i request header fra nettleseren, og spesielt når nb får høyere q-verdi, se bildet under.

![image](https://user-images.githubusercontent.com/46558821/188629766-ee0b7919-2d36-4307-b736-e403246fe119.png)

**Comment by stigbd** [comment]
Default språk, dvs _uten_ accept-language _er_ norsk bokmål. Så det scenariet er støtta i dag. Verifiser feks slik:
```
% curl -I -H "Accept: text/html" https://data.norge.no/vocabulary/public-service-type
HTTP/2 200 
date: Tue, 06 Sep 2022 12:38:18 GMT
content-type: text/html; charset=utf-8
...
content-language: nb
```

Men feilen består i at tjenesten ikkje respekterer accept-language header der fleire språk er angitt med ulike q-faktors:
```
% curl -I -H "Accept: text/html" -H "accept-language: nb-NO;q=0.9,en-GB,en;q=0.8,nb;q=0.7,en-US;q=0.6,da;q=0.5,no;q=0.4" https://data.norge.no/vocabulary/public-service-type
HTTP/2 200 
date: Tue, 06 Sep 2022 12:42:47 GMT
content-type: text/html; charset=utf-8
...
content-language: en
```
```
% curl -I -H "Accept: text/html" -H "accept-language: en-GB,en;q=0.9,nb-NO;q=0.8,nb;q=0.7,en-US;q=0.6,da;q=0.5,no;q=0.4" https://data.norge.no/vocabulary/public-service-type
HTTP/2 200 
date: Tue, 06 Sep 2022 12:43:52 GMT
content-type: text/html; charset=utf-8
...
content-language: en
```
Vi fikser.
